services:
  postgres:
    image: postgres:16
    container_name: mindurcode-db
    environment:
      POSTGRES_DB: mindurcode
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - mindurcode_data:/var/lib/postgresql/data

volumes:
  mindurcode_data:
