spring.application.name=mindurcode

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/mindurcode
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Ollama
ollama.base-url=http://localhost:11434
ollama.model=qwen2.5-coder:7b
